// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ullhsvewamcqxmfsgfjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsbGhzdmV3YW1jcXhtZnNnZmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzOTA0NDgsImV4cCI6MjA2Mzk2NjQ0OH0.p2-ta03KdfqW3bIoAoTbLSESijGIvVE-O1HVTUUqmws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});